version: "3.7"
services:
  app:
    image: ghcr.io/jeongdawun/fastapi-server:latest
    container_name: fastapi-server
    ports:
      - 8000:8000
    networks:
      - app

networks:
  app:
    driver: bridge
